- name: Disable swap
  command: swapoff -a
  changed_when: false

- name: Comment swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^\s*([^#]\S+)\s+swap\s+'
    replace: '# \1 swap '

- name: Sysctl ip_forward
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.ipv4.ip_forward = 1
  notify: Reload sysctl

- name: Base packages
  apt:
    name: [curl, ca-certificates, apt-transport-https, gnupg, lsb-release]
    state: present
    update_cache: yes

