---
- name: Apply Tigera operator (Calico)
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  command: >
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/tigera-operator.yaml

- name: Wait for tigera-operator to be available
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    kubectl -n tigera-operator rollout status deployment/tigera-operator --timeout=300s
  register: tigera_rollout
  retries: 10
  delay: 10
  until: tigera_rollout.rc == 0

- name: Wait for Calico CRDs to exist
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    kubectl get crd installations.operator.tigera.io
  register: calico_crd_check
  retries: 30
  delay: 5
  until: calico_crd_check.rc == 0

- name: Apply Calico custom resources (default IPPool)
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  command: >
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/custom-resources.yaml

- name: Wait for calico-system namespace
  become: yes
  environment: { KUBECONFIG: /etc/kubernetes/admin.conf }
  shell: kubectl get ns calico-system
  register: ns_check
  retries: 30
  delay: 5
  until: ns_check.rc == 0

- name: Wait for calico-node DaemonSet to be ready
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    kubectl -n calico-system rollout status ds/calico-node --timeout=600s
  register: calico_node_rollout
  retries: 10
  delay: 10
  until: calico_node_rollout.rc == 0

- name: Wait for CoreDNS to be ready
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: kubectl -n kube-system rollout status deploy/coredns --timeout=600s
  register: coredns_rollout
  retries: 10
  delay: 10
  until: coredns_rollout.rc == 0
