---
- name: Base OS + container runtime + k8s packages
  hosts: all
  become: yes
  tags: [cluster]
  roles:
    - role: common
    - role: containerd
    - role: kube-packages

- name: Initialize control plane
  hosts: control
  become: yes
  tags: [cluster]
  roles:
    - role: kubeadm-init

- name: Join worker nodes
  hosts: workers
  become: yes
  tags: [cluster]
  roles:
    - role: kubeadm-join

- name: Install Calico CNI
  hosts: control
  become: yes
  tags: [calico]
  roles:
    - role: calico

- name: Install MetalLB
  hosts: control
  become: yes
  tags: [metallb]
  roles:
    - role: metallb

- name: Install ingress-nginx
  hosts: control
  become: yes
  tags: [ingress]
  roles:
    - role: ingress-nginx

- name: Install monitoring stack
  hosts: control
  become: yes
  tags: [monitoring]
  roles:
    - role: monitoring

- name: Install local-path StorageClass (default)
  hosts: control
  become: yes
  tags: [storage]
  roles:
    - role: storage-localpath

- name: Deploy app stack (PostgreSQL + web)
  hosts: control
  become: yes
  tags: [appstack]
  roles:
    - role: app-stack
