- hosts: all
  become: yes
  roles:
    - common
    - containerd
    - kube-packages

- hosts: control
  become: yes
  roles:
    - kubeadm-init
    - calico

- hosts: workers
  become: yes
  roles:
    - kubeadm-join

- hosts: control
  become: yes
  roles:
    - metallb
    - ingress-nginx
