name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=terraform fmt -check
      - run: terraform -chdir=terraform init -backend=false
      - run: terraform -chdir=terraform validate
      - uses: ansible/ansible-lint-action@v6
        with: { path: "ansible" }

